### ISSUE TITLE
Migration to nullsafety

### ISSUE THREAD

**Issue by RatakondalaArun** [iamsalnikov/colorize#7]
- https://dart.dev/null-safety/migration-guide#step1-wait
- https://medium.com/dartlang/announcing-dart-null-safety-beta-87610fee6730

**Comment by kallaspriit** [comment]
It seems the null-safety version has not been published yet?

**Comment by evanweible-wf** [comment]
Hi @iamsalnikov, would it be possible to get the null-safety version published?

**Comment by iamsalnikov** [comment]
@evanweible-wf, done ✅

**Comment by evanweible-wf** [comment]
Thank you!
